model:
  target: model.unet.DiffusionModel
  params:
    timestep_embed: 16
    size: [64, 64]
    num_classes: 3
    in_channels: 3
    out_channels: 3
    base_hidden_channels: 128
    n_layers: 2
    chan_multiplier: [1, 2]
    inner_layers: [3, 4]
    attention_layers: [False, True]

diffusion:
  target: model.diffusion.GaussianDiffusion
  params:
    image_size: 64

training:
  learning_rate: 3e-4
  batch_size: 64

data:
  target: data.ffhq.FFHQDataset
  params:
    root: ./dataset/ffhq-128
