model:
  target: model.openai.openai.UNetModel
  params:
    image_size: [64, 64]
    in_channels: 3
    out_channels: 3
    model_channels: 64
    num_res_blocks: 2
    channel_mult: [1,2,2,4]
    attention_resolutions: [16]
    use_scale_shift_norm: True
    z_dim: 512

encoder:
  target: model.openai.openai.EncoderUNetModel
  params:
    image_size: [64, 64]
    pool: spatial_v2
    in_channels: 3
    out_channels: 512
    model_channels: 64
    num_res_blocks: 2
    channel_mult: [1,2,4,4,8]
    attention_resolutions: [16]
    use_scale_shift_norm: True

diffusion:
  target: model.diffusion.AutoEncoderGaussianDiffusion
  params:
    image_size: 64
    timesteps: 1000
    loss_type: l2


training:
  batch_size: 128
  learning_rate: 1e-4
  save_every: 10000
  sample_every: 500
  grandient_accumulation_steps: 1
  grad_clip: 1
  ema_decay: 0.995
  epochs: 500
  fp16: False
  scheduler: none



data:
  target: data.ffhq.FFHQDataset
  params:
    root: ./dataset/ffhq-64
