model:
  target: model.unet.DiffusionModel
  params:
    timestep_embeds: 16
    in_channels: 3
    out_channels: 3
    base_hidden_channels: 128
    n_layers: 4
    chan_multiplier: [1, 2, 2, 4]
    inner_layers: [3, 4, 4, 6]
    attention_layers: [False, False, False, True]
diffusion:
  target: model.diffusion.GaussianDiffusion
  params:
    image_size: 256
