model:
  target: model.unet.UNet
  params:
    timestep_embed: 16
    size: [64, 64]
    in_channels: 3
    out_channels: 3
    base_hidden_channels: 64
    n_layers: 4
    chan_multiplier: [1, 2, 4, 8]
    inner_layers: [3, 3, 3, 3]
    attention_layers: [False, False, False, True]
    z_dim: 512

encoder:
    target: model.latent_encoder.LatentEncoder
    params:
      in_channels: 3
      base_hidden_channels: 64
      n_layers: 5
      chan_multiplier: [1, 2, 4, 8, 8]
      inner_layers: [2, 3, 3, 3, 3]
      attention_layers: [False, False, False, True, False]
      z_dim: 512
      dropout: 0.1

diffusion:
  target: model.diffusion.AutoEncoderGaussianDiffusion
  params:
    image_size: 64
    timesteps: 1000


training:
  learning_rate: 2e-5
  batch_size: 100
  save_every: 1000
  sample_every: 500
  grandient_accumulation_steps: 1
  grad_clip: 0.1
  ema_decay: 0.995
  fp16: False


data:
  target: data.ffhq.FFHQDataset
  params:
    root: ./dataset/ffhq-64
