model:
  target: model.unet.UNet
  params:
    timestep_embed: 16
    size: [28, 28]
    in_channels: 1
    out_channels: 1
    base_hidden_channels: 32
    n_layers: 2
    chan_multiplier: [1, 2]
    inner_layers: [2, 2]
    attention_layers: [False, True]
    z_dim: 32

encoder:
    target: model.latent_encoder.LatentEncoder
    params:
      in_channels: 1
      base_hidden_channels: 32
      n_layers: 2
      chan_multiplier: [1,2]
      inner_layers: [1,2]
      attention_layers: [ False, False , True, True]
      z_dim: 32
      dropout: 0.1

diffusion:
  target: model.diffusion.AutoEncoderGaussianDiffusion
  params:
    image_size: 28
    timesteps: 1000


training:
  learning_rate: 2e-5
  batch_size: 256
  save_every: 1000
  sample_every: 500

data:
  target: data.mnist.MNIST
  params:
    root: /media/lleonard/big_slow_disk/datasets/mnist