model:
  target: model.unet.DiffusionModel
  params:
    timestep_embed: 16
    num_classes: 10
    in_channels: 1
    out_channels: 1
    base_hidden_channels: 32
    n_layers: 2
    chan_multiplier: [1, 2]
    inner_layers: [2, 2]
    attention_layers: [False, True]
diffusion:
  target: model.diffusion.GaussianDiffusion
  params:
    image_size: 28
    timesteps: 1000

training:
  learning_rate: 1e-5
  batch_size: 256

data:
  target: torchvision.datasets.MNIST
  params:
    train: True
    download: True
    root: /media/lleonard/big_slow_disk/datasets/mnist