model:
  target: model.unet.UNet
  params:
    timestep_embed: 16
    size: [32, 32]
    in_channels: 1
    out_channels: 1
    base_hidden_channels: 64
    n_layers: 3
    inner_layers: [3,5,5]
    chan_multiplier: [1,2,4]
    attention_layers: [False, True, True]
    z_dim: 256

encoder:
    target: model.latent_encoder.LatentEncoder
    params:
      in_channels: 1
      base_hidden_channels: 64
      n_layers: 4
      chan_multiplier: [1,2,4,4]
      inner_layers: [3,3,5,5]
      linear_layers: [704, 512, 256]
      attention_layers: [False, False, True, True]
      z_dim: 256
      dropout: 0.1

diffusion:
  target: model.diffusion.AutoEncoderGaussianDiffusion
  params:
    image_size: 32
    timesteps: 1000


training:
  scheduler: none
  learning_rate: 1e-4
  batch_size: 256
  save_every: 1000
  sample_every: 500
  grandient_accumulation_steps: 1
  grad_clip: 0.1
  ema_decay: 0.995
  fp16: True

data:
  target: data.mnist.QMNIST
  params:
    root: /media/lleonard/big_slow_disk/datasets/qmnist
    size: [32, 32]