model:
  target: model.unet.UNet
  params:
    timestep_embed: 16
    size: [28, 28]
    in_channels: 1
    out_channels: 1
    base_hidden_channels: 32
    n_layers: 2
    chan_multiplier: [1, 2]
    inner_layers: [2, 2]
    attention_layers: [False, True]
    z_dim: 128

diffusion:
  target: model.diffusion.AutoEncoderGaussianDiffusion
  params:
    image_size: 28
    timesteps: 1000
    encoder_params:
      in_channels: 1
      out_channels: 1
      base_hidden_channels: 32
      n_layers: 4
      chan_multiplier: [ 1,2,2, 4]
      inner_layers: [ 1,2,2, 4]
      attention_layers: [ False, False , True, True]
      z_dim: 128

training:
  learning_rate: 1e-4
  batch_size: 256

data:
  target: torchvision.datasets.MNIST
  params:
    train: True
    download: True
    root: /media/lleonard/big_slow_disk/datasets/mnist