model:
  target: model.unet.UNet
  params:
    timestep_embed: 16
    size: [28, 28]
    in_channels: 1
    out_channels: 1
    base_hidden_channels: 64
    n_layers: 2
    chan_multiplier: [2, 2]
    inner_layers: [2, 4]
    attention_layers: [False, False]
    z_dim: 512

encoder:
    target: model.latent_encoder.LatentEncoder
    params:
      in_channels: 1
      base_hidden_channels: 128
      n_layers: 2
      chan_multiplier: [2,2]
      inner_layers: [2,4]
      attention_layers: [False, False]
      z_dim: 512
      linear_layers: [512, 512]
      dropout: 0.0

diffusion:
  target: model.diffusion.AutoEncoderGaussianDiffusion
  params:
    image_size: 28
    timesteps: 1000


training:
  scheduler: none
  learning_rate: 1e-4
  batch_size: 256
  save_every: 1000
  sample_every: 500
  grandient_accumulation_steps: 2
  grad_clip: 1
  ema_decay: 0.995
  fp16: True

data:
  target: data.mnist.MNIST
  params:
    root: /media/lleonard/big_slow_disk/datasets/mnist