model:
  target: model.openai.openai.UNetModel
  params:
    image_size: [8, 8]
    in_channels: 2
    out_channels: 1
    model_channels: 64
    num_res_blocks: 2
    channel_mult: [1,2]
    attention_resolutions: [8]
    use_scale_shift_norm: True
    z_dim: 256

encoder:
  target: model.openai.openai.EncoderUNetModel
  params:
    image_size: [32, 32]
    pool: spatial_v2
    in_channels: 1
    out_channels: 256
    model_channels: 64
    num_res_blocks: 2
    channel_mult: [1,2]
    attention_resolutions: [8]
    use_scale_shift_norm: True

diffusion:
  target: model.diffusion.PatchAutoEncoderGaussianDiffusion
  params:
    size: [32, 32]
    patch_size: 8
    timesteps: 1000

training:
  scheduler: none
  learning_rate: 1e-4
  encoder_learning_rate: 1e-4
  batch_size: 256
  save_every: 1000
  sample_every: 500
  grandient_accumulation_steps: 1
  grad_clip: 1
  ema_decay: 0.995
  fp16: False

data:
  target: data.mnist.QMNIST
  params:
    root: /media/lleonard/big_slow_disk/datasets/qmnist
    size: [32, 32]
